emit:
  - "@typespec/openapi3"
  - "@typespec/http-server-js"
options:
  "@typespec/openapi3":
    emitter-output-dir: "{project-root}/../docs/static/redoc"
    openapi-versions:
      - 3.0.0
    file-type: yaml
    output-file: "openapi-mineauth.yaml"
    omit-unreachable-types: true
    include-x-typespec-name: "never"
    new-line: lf
  "@typespec/http-server-js":
    emitter-output-dir: "{output-dir}/server/js"
